version: '3.7'

services:
  app:
    build: .
    image: &app app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: &envfile
      - env.env
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: library/postgres:13-alpine
    env_file: *envfile
    ports:
      - "5432:5432"

  celery:
    build: .
    image: *app
    command: celery -A DjangoTaskEnjoyPro worker
    env_file: *envfile
    restart: "no"
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq
    env_file: *envfile
    ports:
      - 5672:5672
